version: '2'
services:
  web:
    build:
      context: git@github.com:Runnable/Dockerfile-Testing-Kahn
      dockerfile: LoggerDockerfile
    container_name: web
    environment:
      - TESTFOO=true
      - TESTBar=false
    env_file:
      - .barEnv
  web1:
    build:
      context: git@github.com:Runnable/Dockerfile-Testing-Kahn
      dockerfile: LoggerDockerfile
    container_name: web
    environment:
      - TESTFOO=false
      - TESTBar=true
    env_file:
      - .barEnv
  rethinkdb3:
    image: 'rethinkdb'
  rethinkdb4:
    image: 'rethinkdb'
