version: '2'
services:
  web:
    build: 
      context: git@github.com:Runnable/Dockerfile-Testing-Kahn-1
      dockerfile: Dockerfile-1
    container_name: web
    environment:
      - TESTFOO=true
      - TESTBar=false
    env_file:
      - ./env/foo/.env
  web1:
    build:
      context: git@github.com:Runnable/Dockerfile-Testing-Kahn
      dockerfile: LoggerDockerfile
    container_name: web
    environment:
      - TESTFOO=false
      - TESTBar=true
    env_file:
      - ./env/bar/.env
  rethinkdb3:
    image: 'rethinkdb'
  rethinkdb4:
    image: 'rethinkdb'
